spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
