server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/demoxie/service-configurations.git
          search-paths: /
          username: shadrachadamuul@gmail.com
          password: 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
          clone-on-start: true
          repos:
              gateway:
                pattern:
                  - gateway
                search-paths:
                  - gateway
                uri: https://github.com/demoxie/service-configurations.git
                username: ${spring.cloud.config.server.git.username}
                password: ${spring.cloud.config.server.git.password}
              account-service:
                pattern:
                  - account-service
                search-paths:
                  - account-service
                uri: https://github.com/demoxie/service-configurations.git
                username: ${spring.cloud.config.server.git.username}
                password: ${spring.cloud.config.server.git.password}
              authorization-server:
                pattern:
                  - authorization-server
                search-paths:
                  - authorization-server
                uri: https://github.com/demoxie/service-configurations.git
                username: ${spring.cloud.config.server.git.username}
                password: ${spring.cloud.config.server.git.password}
              transaction-service:
                pattern:
                  - transaction-service
                search-paths:
                  - transaction-service
                uri: https://github.com/demoxie/service-configurations.git
                username: ${spring.cloud.config.server.git.username}
                password: ${spring.cloud.config.server.git.password}
          refresh-rate: 1000
      discovery:
        service-id: config-server
  application:
    name: config-server



management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/