spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 3000
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 60000
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 0
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
